# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: > # DevOps, ALM, Continuous Deployment, Delivery, Integration with a touch of Architecture and Coding
email: taavik@melborp.net
description: > # Welcome to my corner of gems, tips and trinkets regarding
  DevOps, Application Lifecycle Management, Contionuous Deployment, Delivery and Integration,
  Build and bits and pieces mixed with architecture, coding and technology topics. I try to 
  write what i find useful, like to share or need written down somewhere so i dont have to keep
  it in my already overloaded head. You are welcome to dig deep and hopefully find something useful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://melborp.net" # the base hostname & protocol for your site
twitter_username: melborp
github_username:  melborp

# Build settings
markdown: kramdown
theme: minima
repository: melborp/melborp.github.io