# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ALM and Coding @ melborp.net
email: taavik@melborp.net
description: > # this means to ignore newlines until "baseurl:"
  Taavi Koosaar | Taavi Kõosaar - thoughts and experiences in 
  the world of ALM, architecture, programming in deep and general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://melborp.net" # the base hostname & protocol for your site
twitter_username: melborp
github_username:  melborp
<<<<<<< HEAD
=======
paginate: 5
>>>>>>> 2f65d61855935beb8626ec19487e1938079ce65b

# Build settings
markdown: kramdown
highlighter: rouge
